version: '3'
services:
  php:
    restart: always
    build: ./DockerCompose-main
    ports:
      - 5555:80
    depends_on:
      - mysql
  mysql:
    restart: always
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=user_db
    ports:
      - 3306:3306
    volumes:
      - mysql_data:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1
volumes:
  mysql_data: 